-- Complete Healthcare Module
CREATE TABLE IF NOT EXISTS `medical_records` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `appointment_id` BIGINT UNSIGNED,
  `record_number` VARCHAR(50) NOT NULL UNIQUE,
  `record_date` DATE NOT NULL,
  `doctor_id` BIGINT UNSIGNED,
  `chief_complaint` TEXT,
  `present_illness_history` TEXT,
  `past_medical_history` TEXT,
  `family_history` TEXT,
  `social_history` TEXT,
  `allergies` TEXT,
  `current_medications` TEXT,
  `physical_examination` TEXT,
  `diagnosis` TEXT,
  `diagnosis_codes` JSON,
  `treatment` TEXT,
  `prescriptions` JSON,
  `lab_orders` JSON,
  `imaging_orders` JSON,
  `follow_up_instructions` TEXT,
  `follow_up_date` DATE,
  `record_status` ENUM('draft', 'completed', 'reviewed', 'signed') DEFAULT 'draft',
  `is_signed` BOOLEAN DEFAULT FALSE,
  `signed_at` TIMESTAMP,
  `signed_by` BIGINT UNSIGNED,
  `attachments` JSON,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `medical_records_tenant_idx` (`tenant_id`),
  INDEX `medical_records_patient_idx` (`patient_id`),
  INDEX `medical_records_doctor_idx` (`doctor_id`),
  INDEX `medical_records_date_idx` (`record_date`)
);

CREATE TABLE IF NOT EXISTS `prescriptions_detail` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `medical_record_id` BIGINT UNSIGNED,
  `prescription_number` VARCHAR(50) NOT NULL UNIQUE,
  `prescription_date` DATE NOT NULL,
  `doctor_id` BIGINT UNSIGNED NOT NULL,
  `medication_name` VARCHAR(255) NOT NULL,
  `medication_code` VARCHAR(100),
  `generic_name` VARCHAR(255),
  `strength` VARCHAR(50),
  `dosage_form` VARCHAR(50),
  `route` VARCHAR(50),
  `dosage` VARCHAR(100) NOT NULL,
  `frequency` VARCHAR(100) NOT NULL,
  `duration` VARCHAR(100),
  `duration_days` INT,
  `quantity` INT NOT NULL,
  `refills` INT DEFAULT 0,
  `instructions` TEXT,
  `indications_for_use` TEXT,
  `warnings` TEXT,
  `is_controlled_substance` BOOLEAN DEFAULT FALSE,
  `controlled_substance_schedule` VARCHAR(10),
  `substitution_allowed` BOOLEAN DEFAULT TRUE,
  `status` ENUM('active', 'dispensed', 'partial', 'discontinued', 'expired', 'cancelled') DEFAULT 'active',
  `dispensed_at` TIMESTAMP,
  `dispensed_by` BIGINT UNSIGNED,
  `dispensed_quantity` INT,
  `pharmacy_notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `prescriptions_detail_tenant_idx` (`tenant_id`),
  INDEX `prescriptions_detail_patient_idx` (`patient_id`),
  INDEX `prescriptions_detail_status_idx` (`status`)
);

CREATE TABLE IF NOT EXISTS `vital_signs` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `medical_record_id` BIGINT UNSIGNED,
  `appointment_id` BIGINT UNSIGNED,
  `recorded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `temperature` DECIMAL(5,2),
  `temperature_unit` VARCHAR(1) DEFAULT 'C',
  `blood_pressure_systolic` INT,
  `blood_pressure_diastolic` INT,
  `heart_rate` INT,
  `respiratory_rate` INT,
  `oxygen_saturation` DECIMAL(5,2),
  `weight` DECIMAL(8,2),
  `weight_unit` VARCHAR(3) DEFAULT 'kg',
  `height` DECIMAL(8,2),
  `height_unit` VARCHAR(3) DEFAULT 'cm',
  `bmi` DECIMAL(5,2),
  `pain_score` INT,
  `glucose_level` DECIMAL(6,2),
  `notes` TEXT,
  `recorded_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `vital_signs_tenant_idx` (`tenant_id`),
  INDEX `vital_signs_patient_idx` (`patient_id`)
);

CREATE TABLE IF NOT EXISTS `lab_results` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `lab_order_id` BIGINT UNSIGNED,
  `result_number` VARCHAR(50) NOT NULL UNIQUE,
  `test_name` VARCHAR(255) NOT NULL,
  `test_code` VARCHAR(100),
  `test_category` VARCHAR(100),
  `specimen_type` VARCHAR(100),
  `collection_date` TIMESTAMP,
  `received_date` TIMESTAMP,
  `reported_date` TIMESTAMP,
  `result` TEXT,
  `result_value` VARCHAR(255),
  `result_unit` VARCHAR(50),
  `reference_range` VARCHAR(255),
  `is_abnormal` BOOLEAN DEFAULT FALSE,
  `abnormal_flag` VARCHAR(10),
  `interpretation` TEXT,
  `status` ENUM('pending', 'in_progress', 'completed', 'reviewed', 'cancelled') DEFAULT 'pending',
  `notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `lab_results_tenant_idx` (`tenant_id`),
  INDEX `lab_results_patient_idx` (`patient_id`)
);

CREATE TABLE IF NOT EXISTS `healthcare_billing` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `appointment_id` BIGINT UNSIGNED,
  `medical_record_id` BIGINT UNSIGNED,
  `bill_number` VARCHAR(50) NOT NULL UNIQUE,
  `bill_date` DATE NOT NULL,
  `consultation_fee` DECIMAL(18,4) DEFAULT 0,
  `procedure_fee` DECIMAL(18,4) DEFAULT 0,
  `medication_fee` DECIMAL(18,4) DEFAULT 0,
  `lab_fee` DECIMAL(18,4) DEFAULT 0,
  `imaging_fee` DECIMAL(18,4) DEFAULT 0,
  `other_charges` DECIMAL(18,4) DEFAULT 0,
  `subtotal` DECIMAL(18,4) NOT NULL,
  `discount_amount` DECIMAL(18,4) DEFAULT 0,
  `tax_amount` DECIMAL(18,4) DEFAULT 0,
  `total_amount` DECIMAL(18,4) NOT NULL,
  `insurance_coverage` DECIMAL(18,4) DEFAULT 0,
  `patient_responsibility` DECIMAL(18,4),
  `paid_amount` DECIMAL(18,4) DEFAULT 0,
  `balance_due` DECIMAL(18,4),
  `payment_status` ENUM('unpaid', 'partial', 'paid', 'refunded', 'cancelled') DEFAULT 'unpaid',
  `invoice_id` BIGINT UNSIGNED,
  `notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `healthcare_billing_tenant_idx` (`tenant_id`),
  INDEX `healthcare_billing_patient_idx` (`patient_id`),
  INDEX `healthcare_billing_status_idx` (`payment_status`)
);

-- Workshop Enhancements
CREATE TABLE IF NOT EXISTS `warranties` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `vehicle_id` BIGINT UNSIGNED,
  `job_card_id` BIGINT UNSIGNED,
  `warranty_number` VARCHAR(50) NOT NULL UNIQUE,
  `warranty_type` ENUM('manufacturer', 'extended', 'service', 'parts', 'labor') NOT NULL,
  `coverage_type` VARCHAR(100),
  `provider_name` VARCHAR(255),
  `provider_contact` VARCHAR(255),
  `start_date` DATE NOT NULL,
  `end_date` DATE,
  `mileage_limit` INT,
  `current_mileage` INT,
  `covered_items` JSON,
  `exclusions` TEXT,
  `deductible` DECIMAL(10,2) DEFAULT 0,
  `coverage_amount` DECIMAL(10,2),
  `status` ENUM('active', 'expired', 'cancelled', 'claimed', 'void') DEFAULT 'active',
  `document_url` TEXT,
  `notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `warranties_tenant_idx` (`tenant_id`),
  INDEX `warranties_vehicle_idx` (`vehicle_id`),
  INDEX `warranties_status_idx` (`status`)
);

CREATE TABLE IF NOT EXISTS `warranty_claims` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `warranty_id` BIGINT UNSIGNED NOT NULL,
  `vehicle_id` BIGINT UNSIGNED NOT NULL,
  `job_card_id` BIGINT UNSIGNED,
  `claim_number` VARCHAR(50) NOT NULL UNIQUE,
  `claim_date` DATE NOT NULL,
  `failure_description` TEXT NOT NULL,
  `failure_date` DATE,
  `mileage_at_failure` INT,
  `parts_replaced` JSON,
  `labor_hours` DECIMAL(8,2),
  `parts_cost` DECIMAL(10,2) DEFAULT 0,
  `labor_cost` DECIMAL(10,2) DEFAULT 0,
  `total_cost` DECIMAL(10,2) NOT NULL,
  `claimed_amount` DECIMAL(10,2),
  `approved_amount` DECIMAL(10,2) DEFAULT 0,
  `status` ENUM('draft', 'submitted', 'pending_approval', 'approved', 'rejected', 'paid', 'partial') DEFAULT 'draft',
  `submitted_at` TIMESTAMP,
  `approved_at` TIMESTAMP,
  `paid_at` TIMESTAMP,
  `rejection_reason` TEXT,
  `attachments` JSON,
  `notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `warranty_claims_tenant_idx` (`tenant_id`),
  INDEX `warranty_claims_warranty_idx` (`warranty_id`),
  INDEX `warranty_claims_vehicle_idx` (`vehicle_id`),
  INDEX `warranty_claims_status_idx` (`status`)
);

CREATE TABLE IF NOT EXISTS `service_reminders` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `vehicle_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED,
  `reminder_type` ENUM('scheduled_maintenance', 'oil_change', 'tire_rotation', 'inspection', 'registration_renewal', 'insurance_renewal', 'warranty_expiry', 'custom') NOT NULL,
  `service_title` VARCHAR(255) NOT NULL,
  `service_description` TEXT,
  `due_date` DATE,
  `due_mileage` INT,
  `current_mileage` INT,
  `reminder_interval_days` INT,
  `reminder_interval_miles` INT,
  `last_service_date` DATE,
  `last_service_mileage` INT,
  `priority` ENUM('low', 'normal', 'high', 'critical') DEFAULT 'normal',
  `notification_method` JSON,
  `auto_schedule` BOOLEAN DEFAULT FALSE,
  `estimated_cost` DECIMAL(10,2),
  `status` ENUM('active', 'sent', 'scheduled', 'completed', 'snoozed', 'cancelled') DEFAULT 'active',
  `sent_at` TIMESTAMP,
  `snoozed_until` DATE,
  `completed_at` TIMESTAMP,
  `completed_job_card_id` BIGINT UNSIGNED,
  `notes` TEXT,
  `created_by` BIGINT UNSIGNED,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `service_reminders_tenant_idx` (`tenant_id`),
  INDEX `service_reminders_vehicle_idx` (`vehicle_id`),
  INDEX `service_reminders_status_idx` (`status`)
);

CREATE TABLE IF NOT EXISTS `vehicle_parts` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `part_number` VARCHAR(100) NOT NULL,
  `part_name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `manufacturer` VARCHAR(255),
  `category` VARCHAR(100),
  `vehicle_make` VARCHAR(100),
  `vehicle_model` VARCHAR(100),
  `unit_price` DECIMAL(10,2) NOT NULL,
  `cost_price` DECIMAL(10,2),
  `quantity_in_stock` INT DEFAULT 0,
  `reorder_level` INT DEFAULT 5,
  `supplier_id` BIGINT UNSIGNED,
  `warehouse_location` VARCHAR(100),
  `is_active` BOOLEAN DEFAULT TRUE,
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `vehicle_parts_tenant_idx` (`tenant_id`),
  INDEX `vehicle_parts_number_idx` (`part_number`),
  INDEX `vehicle_parts_category_idx` (`category`)
);

CREATE TABLE IF NOT EXISTS `parts_usage` (
  `id` SERIAL PRIMARY KEY,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `job_card_id` BIGINT UNSIGNED NOT NULL,
  `part_id` BIGINT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `is_warranty_claim` BOOLEAN DEFAULT FALSE,
  `warranty_claim_id` BIGINT UNSIGNED,
  `issued_by` BIGINT UNSIGNED,
  `issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `parts_usage_tenant_idx` (`tenant_id`),
  INDEX `parts_usage_job_card_idx` (`job_card_id`)
);
