// ALL AVAILABLE MODULES FOR COMPANY SELECTION
// Company can choose which modules to enable during signup

export const ALL_MODULES = [
  // CORE MODULES (Always available)
  {
    id: "accounting",
    name: "Accounting",
    nameAr: "المحاسبة",
    description: "Chart of Accounts, Journals, Financial Reports",
    descriptionAr: "دليل الحسابات، القيود، التقارير المالية",
    icon: "Calculator",
    category: "core",
    isCore: true,
  },
  {
    id: "inventory",
    name: "Inventory",
    nameAr: "المخزون",
    description: "Products, Stock, Transfers, Adjustments",
    descriptionAr: "المنتجات، المخزون، التحويلات، التسويات",
    icon: "Package",
    category: "core",
    isCore: true,
  },
  {
    id: "sales",
    name: "Sales",
    nameAr: "المبيعات",
    description: "Invoices, Quotations, Orders, Customers",
    descriptionAr: "الفواتير، عروض الأسعار، الطلبات، العملاء",
    icon: "ShoppingCart",
    category: "core",
    isCore: true,
  },
  {
    id: "purchase",
    name: "Purchase",
    nameAr: "المشتريات",
    description: "Purchase Orders, GRN, Suppliers, Payments",
    descriptionAr: "أوامر الشراء، استلام البضائع، الموردين، المدفوعات",
    icon: "ShoppingBag",
    category: "core",
    isCore: true,
  },
  {
    id: "hrm",
    name: "HRM & Payroll",
    nameAr: "الموارد البشرية",
    description: "Employees, Payroll, Attendance, Leave, GOSI, WPS",
    descriptionAr: "الموظفين، الرواتب، الحضور، الإجازات، GOSI، WPS",
    icon: "Users",
    category: "core",
    isCore: true,
  },

  // POS MODULES
  {
    id: "pos_retail",
    name: "POS - Retail",
    nameAr: "نقاط البيع - تجزئة",
    description: "Point of Sale for retail stores",
    descriptionAr: "نقطة بيع لمحلات التجزئة",
    icon: "Store",
    category: "pos",
    isCore: false,
  },
  {
    id: "pos_restaurant",
    name: "POS - Restaurant",
    nameAr: "نقاط البيع - مطعم",
    description: "Restaurant POS with tables, orders, kitchen",
    descriptionAr: "نقطة بيع مطعم مع الطاولات والطلبات",
    icon: "UtensilsCrossed",
    category: "pos",
    isCore: false,
  },
  {
    id: "pos_pharmacy",
    name: "POS - Pharmacy",
    nameAr: "نقاط البيع - صيدلية",
    description: "Pharmacy POS with prescriptions, batch tracking",
    descriptionAr: "نقطة بيع صيدلية مع الوصفات وتتبع الدفعات",
    icon: "Pill",
    category: "pos",
    isCore: false,
  },

  // INDUSTRY VERTICALS
  {
    id: "healthcare",
    name: "Hospital/Clinic",
    nameAr: "المستشفى/العيادة",
    description: "Patients, EMR, Appointments, Prescriptions, Lab, Billing",
    descriptionAr: "المرضى، السجل الطبي، المواعيد، الوصفات، المختبر، الفواتير",
    icon: "Hospital",
    category: "vertical",
    isCore: false,
  },
  {
    id: "workshop",
    name: "Workshop/Garage",
    nameAr: "ورشة/كراج",
    description: "Vehicle repair, Job cards, Warranty, Service reminders",
    descriptionAr: "صيانة المركبات، بطاقات العمل، الضمان، تذكيرات الخدمة",
    icon: "Wrench",
    category: "vertical",
    isCore: false,
  },
  {
    id: "construction",
    name: "Construction",
    nameAr: "المقاولات",
    description: "Projects, BOQ, WBS, Variations, Payment certificates",
    descriptionAr: "المشاريع، جدول الكميات، الاختلافات، شهادات الدفع",
    icon: "HardHat",
    category: "vertical",
    isCore: false,
  },
  {
    id: "education",
    name: "School/University",
    nameAr: "مدرسة/جامعة",
    description: "Students, Admissions, Fees, Timetables, Report cards",
    descriptionAr: "الطلاب، القبول، الرسوم، الجداول، بطاقات التقارير",
    icon: "GraduationCap",
    category: "vertical",
    isCore: false,
  },
  {
    id: "hotel",
    name: "Hotel",
    nameAr: "فندق",
    description: "Rooms, Bookings, Housekeeping, Folio billing",
    descriptionAr: "الغرف، الحجوزات، التنظيف، الفواتير",
    icon: "Hotel",
    category: "vertical",
    isCore: false,
  },
  {
    id: "real_estate",
    name: "Real Estate",
    nameAr: "العقارات",
    description: "Properties, Leases, Rent invoicing, Maintenance",
    descriptionAr: "العقارات، الإيجارات، فواتير الإيجار، الصيانة",
    icon: "Building2",
    category: "vertical",
    isCore: false,
  },
  {
    id: "transport",
    name: "Transport/Logistics",
    nameAr: "النقل/اللوجستيات",
    description: "Fleet, Drivers, Routes, Shipments, Maintenance",
    descriptionAr: "الأسطول، السائقين، الطرق، الشحنات، الصيانة",
    icon: "Truck",
    category: "vertical",
    isCore: false,
  },
  {
    id: "travel",
    name: "Travel Agency",
    nameAr: "وكالة سفر",
    description: "Bookings, Itineraries, Suppliers, Reconciliation",
    descriptionAr: "الحجوزات، برامج الرحلات، الموردين، التسوية",
    icon: "Plane",
    category: "vertical",
    isCore: false,
  },
  {
    id: "aviation",
    name: "Aviation",
    nameAr: "الطيران",
    description: "Flights, Crew, Aircraft, Parts, Maintenance",
    descriptionAr: "الرحلات، الطاقم، الطائرات، قطع الغيار، الصيانة",
    icon: "PlaneTakeoff",
    category: "vertical",
    isCore: false,
  },

  // ADDITIONAL MODULES
  {
    id: "crm",
    name: "CRM",
    nameAr: "إدارة العملاء",
    description: "Leads, Opportunities, Activities, Pipeline",
    descriptionAr: "العملاء المحتملين، الفرص، الأنشطة",
    icon: "Users2",
    category: "additional",
    isCore: false,
  },
  {
    id: "projects",
    name: "Projects & Tasks",
    nameAr: "المشاريع والمهام",
    description: "Project management, Tasks, Timesheets, Billing",
    descriptionAr: "إدارة المشاريع، المهام، سجلات الوقت",
    icon: "FolderKanban",
    category: "additional",
    isCore: false,
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    nameAr: "التصنيع",
    description: "BOM, Production orders, Work orders, Quality",
    descriptionAr: "قائمة المواد، أوامر الإنتاج، أوامر العمل",
    icon: "Factory",
    category: "additional",
    isCore: false,
  },
  {
    id: "assets",
    name: "Asset Management",
    nameAr: "إدارة الأصول",
    description: "Fixed assets, Depreciation, Maintenance, Fleet",
    descriptionAr: "الأصول الثابتة، الاستهلاك، الصيانة",
    icon: "Package2",
    category: "additional",
    isCore: false,
  },
  {
    id: "helpdesk",
    name: "Helpdesk",
    nameAr: "خدمة العملاء",
    description: "Support tickets, Knowledge base, SLA",
    descriptionAr: "تذاكر الدعم، قاعدة المعرفة",
    icon: "MessageCircleQuestion",
    category: "additional",
    isCore: false,
  },
];

// MODULE CATEGORIES
export const MODULE_CATEGORIES = {
  core: { name: "Core Modules", nameAr: "الوحدات الأساسية", required: true },
  pos: { name: "Point of Sale", nameAr: "نقاط البيع", required: false },
  vertical: { name: "Industry Specific", nameAr: "حسب المجال", required: false },
  additional: { name: "Additional Features", nameAr: "ميزات إضافية", required: false },
};

// DEFAULT MODULES BY INDUSTRY
export const INDUSTRY_DEFAULTS = {
  retail: ["pos_retail", "crm"],
  wholesale: ["pos_retail", "crm"],
  manufacturing: ["manufacturing", "assets"],
  healthcare: ["healthcare", "pos_pharmacy"],
  construction: ["construction", "projects"],
  hospitality: ["hotel", "pos_restaurant"],
  education: ["education"],
  logistics: ["transport", "assets"],
  services: ["crm", "projects", "helpdesk"],
  technology: ["crm", "projects", "helpdesk"],
};
