// ALL AVAILABLE MODULES FOR COMPANY SELECTION
// Company can choose which modules to enable during signup

export const ALL_MODULES = [
  // CORE MODULES (Always available)
  {
    id: "accounting",
    name: "Accounting",
    nameAr: "المحاسبة",
    description: "Chart of Accounts, Journals, Financial Reports",
    descriptionAr: "دليل الحسابات، القيود، التقارير المالية",
    icon: "Calculator",
    category: "core",
    isCore: true,
  },
  {
    id: "inventory",
    name: "Inventory",
    nameAr: "المخزون",
    description: "Products, Stock, Transfers, Adjustments",
    descriptionAr: "المنتجات، المخزون، التحويلات، التسويات",
    icon: "Package",
    category: "core",
    isCore: true,
  },
  {
    id: "sales",
    name: "Sales",
    nameAr: "المبيعات",
    description: "Invoices, Quotations, Orders, Customers",
    descriptionAr: "الفواتير، عروض الأسعار، الطلبات، العملاء",
    icon: "ShoppingCart",
    category: "core",
    isCore: true,
  },
  {
    id: "purchase",
    name: "Purchase",
    nameAr: "المشتريات",
    description: "Purchase Orders, GRN, Suppliers, Payments",
    descriptionAr: "أوامر الشراء، استلام البضائع، الموردين، المدفوعات",
    icon: "ShoppingBag",
    category: "core",
    isCore: true,
  },
  {
    id: "hrm",
    name: "HRM & Payroll",
    nameAr: "الموارد البشرية",
    description: "Employees, Payroll, Attendance, Leave, GOSI, WPS",
    descriptionAr: "الموظفين، الرواتب، الحضور، الإجازات، GOSI، WPS",
    icon: "Users",
    category: "core",
    isCore: true,
  },

  // POS MODULES
  {
    id: "pos_retail",
    name: "POS - Retail",
    nameAr: "نقاط البيع - تجزئة",
    description: "Point of Sale for retail stores",
    descriptionAr: "نقطة بيع لمحلات التجزئة",
    icon: "Store",
    category: "pos",
    isCore: false,
  },
  {
    id: "pos_restaurant",
    name: "POS - Restaurant",
    nameAr: "نقاط البيع - مطعم",
    description: "Restaurant POS with tables, orders, kitchen",
    descriptionAr: "نقطة بيع مطعم مع الطاولات والطلبات",
    icon: "UtensilsCrossed",
    category: "pos",
    isCore: false,
  },
  {
    id: "pos_pharmacy",
    name: "POS - Pharmacy",
    nameAr: "نقاط البيع - صيدلية",
    description: "Pharmacy POS with prescriptions, batch tracking",
    descriptionAr: "نقطة بيع صيدلية مع الوصفات وتتبع الدفعات",
    icon: "Pill",
    category: "pos",
    isCore: false,
  },
  {
    id: "pos_wholesale",
    name: "POS - Wholesale",
    nameAr: "نقاط البيع - جملة",
    description: "Wholesale POS with price lists, credit limits",
    descriptionAr: "نقطة بيع جملة مع قوائم أسعار وحدود ائتمان",
    icon: "Store",
    category: "pos",
    isCore: false,
  },

  // INDUSTRY VERTICALS
  {
    id: "healthcare",
    name: "Hospital/Clinic",
    nameAr: "المستشفى/العيادة",
    description: "Patients, EMR, Appointments, Prescriptions, Lab, Billing",
    descriptionAr: "المرضى، السجل الطبي، المواعيد، الوصفات، المختبر، الفواتير",
    icon: "Hospital",
    category: "vertical",
    isCore: false,
  },
  {
    id: "workshop",
    name: "Workshop/Garage",
    nameAr: "ورشة/كراج",
    description: "Vehicle repair, Job cards, Warranty, Service reminders",
    descriptionAr: "صيانة المركبات، بطاقات العمل، الضمان، تذكيرات الخدمة",
    icon: "Wrench",
    category: "vertical",
    isCore: false,
  },
  {
    id: "construction",
    name: "Construction",
    nameAr: "المقاولات",
    description: "Projects, BOQ, WBS, Variations, Payment certificates",
    descriptionAr: "المشاريع، جدول الكميات، الاختلافات، شهادات الدفع",
    icon: "HardHat",
    category: "vertical",
    isCore: false,
  },
  {
    id: "education",
    name: "School/University",
    nameAr: "مدرسة/جامعة",
    description: "Students, Admissions, Fees, Timetables, Report cards",
    descriptionAr: "الطلاب، القبول، الرسوم، الجداول، بطاقات التقارير",
    icon: "GraduationCap",
    category: "vertical",
    isCore: false,
  },
  {
    id: "hotel",
    name: "Hotel",
    nameAr: "فندق",
    description: "Rooms, Bookings, Housekeeping, Folio billing",
    descriptionAr: "الغرف، الحجوزات، التنظيف، الفواتير",
    icon: "Hotel",
    category: "vertical",
    isCore: false,
  },
  {
    id: "real_estate",
    name: "Real Estate",
    nameAr: "العقارات",
    description: "Properties, Leases, Rent invoicing, Maintenance",
    descriptionAr: "العقارات، الإيجارات، فواتير الإيجار، الصيانة",
    icon: "Building2",
    category: "vertical",
    isCore: false,
  },
  {
    id: "transport",
    name: "Transport/Logistics",
    nameAr: "النقل/اللوجستيات",
    description: "Fleet, Drivers, Routes, Shipments, Maintenance",
    descriptionAr: "الأسطول، السائقين، الطرق، الشحنات، الصيانة",
    icon: "Truck",
    category: "vertical",
    isCore: false,
  },
  {
    id: "travel",
    name: "Travel Agency",
    nameAr: "وكالة سفر",
    description: "Bookings, Itineraries, Suppliers, Reconciliation",
    descriptionAr: "الحجوزات، برامج الرحلات، الموردين، التسوية",
    icon: "Plane",
    category: "vertical",
    isCore: false,
  },
  {
    id: "aviation",
    name: "Aviation",
    nameAr: "الطيران",
    description: "Flights, Crew, Aircraft, Parts, Maintenance",
    descriptionAr: "الرحلات، الطاقم، الطائرات، قطع الغيار، الصيانة",
    icon: "PlaneTakeoff",
    category: "vertical",
    isCore: false,
  },
  {
    id: "hostel",
    name: "Hostel / Staff Accommodation",
    nameAr: "سكن / نزل",
    description: "Rooms, Bookings, Rent billing, Housekeeping, Maintenance",
    descriptionAr: "غرف، حجوزات، فواتير إيجار، نظافة، صيانة",
    icon: "Hotel",
    category: "vertical",
    isCore: false,
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    nameAr: "صيدلية",
    description: "Prescriptions, Medication stock, Expiry tracking, Supplier orders",
    descriptionAr: "وصفات طبية، مخزون أدوية، تتبع صلاحية، طلبات موردين",
    icon: "Pill",
    category: "vertical",
    isCore: false,
  },

  // SAUDI-MARKET VERTICAL WORKSPACES (config-driven — see src/config/verticalWorkspaces.ts)
  {
    id: "fieldservice",
    name: "Facility Mgmt & AMC",
    nameAr: "إدارة المرافق وعقود الصيانة",
    description: "AMC contracts, work orders, SLA, technician dispatch",
    descriptionAr: "عقود صيانة، أوامر عمل، اتفاقيات خدمة، إرسال فنيين",
    icon: "Wrench",
    category: "vertical",
    isCore: false,
  },
  {
    id: "events",
    name: "Events & Entertainment",
    nameAr: "الفعاليات والترفيه",
    description: "Wedding halls, exhibitions, tickets, packages, deposits",
    descriptionAr: "قاعات أفراح، معارض، تذاكر، باقات، عربون",
    icon: "PartyPopper",
    category: "vertical",
    isCore: false,
  },
  {
    id: "agency",
    name: "Marketing Agency",
    nameAr: "وكالة تسويق",
    description: "Campaigns, retainers, approvals, influencer billing",
    descriptionAr: "حملات، عقود شهرية، اعتمادات، فوترة مؤثرين",
    icon: "Megaphone",
    category: "vertical",
    isCore: false,
  },
  {
    id: "professional",
    name: "Professional Services",
    nameAr: "الخدمات المهنية",
    description: "Matters, engagements, deadlines, retainer billing",
    descriptionAr: "قضايا، ارتباطات، مواعيد نهائية، أتعاب",
    icon: "Scale",
    category: "vertical",
    isCore: false,
  },
  {
    id: "agriculture",
    name: "Agriculture & Farms",
    nameAr: "الزراعة والمزارع",
    description: "Plots, crop cycles, livestock, harvest batches",
    descriptionAr: "قطع زراعية، دورات محاصيل، مواشي، حصاد",
    icon: "Sprout",
    category: "vertical",
    isCore: false,
  },
  {
    id: "energy",
    name: "Clean Energy & Solar",
    nameAr: "الطاقة النظيفة",
    description: "Solar installs, EV charging, commissioning, AMC",
    descriptionAr: "طاقة شمسية، شواحن كهربائية، تشغيل، صيانة",
    icon: "SunMedium",
    category: "vertical",
    isCore: false,
  },
  {
    id: "mining",
    name: "Mining & Quarrying",
    nameAr: "التعدين والمحاجر",
    description: "Weighbridge tickets, stockpiles, truck dispatch",
    descriptionAr: "تذاكر ميزان، مخزونات، إرسال شاحنات",
    icon: "Mountain",
    category: "vertical",
    isCore: false,
  },
  {
    id: "marine",
    name: "Marine & Shipping",
    nameAr: "الشحن البحري",
    description: "Shipment files, containers, customs docs, demurrage",
    descriptionAr: "ملفات شحن، حاويات، مستندات جمركية، غرامات تأخير",
    icon: "Ship",
    category: "vertical",
    isCore: false,
  },
  {
    id: "veterinary",
    name: "Veterinary & Pets",
    nameAr: "الطب البيطري",
    description: "Pet profiles, appointments, vaccinations, boarding",
    descriptionAr: "ملفات حيوانات، مواعيد، تطعيمات، إيواء",
    icon: "PawPrint",
    category: "vertical",
    isCore: false,
  },
  {
    id: "nonprofit",
    name: "Nonprofit & Charity",
    nameAr: "الجمعيات الخيرية",
    description: "Campaigns, beneficiary cases, restricted funds",
    descriptionAr: "حملات، حالات مستفيدين، صناديق مقيدة",
    icon: "HeartHandshake",
    category: "vertical",
    isCore: false,
  },
  {
    id: "tailoring",
    name: "Tailoring & Fashion",
    nameAr: "الخياطة والأزياء",
    description: "Measurements, fabric rolls, production, fittings",
    descriptionAr: "مقاسات، أقمشة، إنتاج، بروفات",
    icon: "Shirt",
    category: "vertical",
    isCore: false,
  },
  {
    id: "jewelry",
    name: "Gold & Jewelry",
    nameAr: "الذهب والمجوهرات",
    description: "Gold rates, weight/carat, making charges, buyback",
    descriptionAr: "أسعار الذهب، وزن وعيار، مصنعية، إعادة شراء",
    icon: "Gem",
    category: "vertical",
    isCore: false,
  },
  {
    id: "repair",
    name: "Electronics Repair",
    nameAr: "صيانة الإلكترونيات",
    description: "Repair tickets, IMEI tracking, approvals, warranty",
    descriptionAr: "تذاكر صيانة، تتبع IMEI، موافقات، ضمان",
    icon: "Smartphone",
    category: "vertical",
    isCore: false,
  },
  {
    id: "furniture",
    name: "Furniture & Carpentry",
    nameAr: "الأثاث والنجارة",
    description: "Site measurement, custom orders, production, install",
    descriptionAr: "قياس مواقع، طلبات مخصصة، إنتاج، تركيب",
    icon: "Armchair",
    category: "vertical",
    isCore: false,
  },
  {
    id: "printing",
    name: "Printing & Signage",
    nameAr: "الطباعة واللوحات",
    description: "Artwork approvals, sqm pricing, machine jobs",
    descriptionAr: "اعتماد تصاميم، تسعير بالمتر، مهام مكائن",
    icon: "Printer",
    category: "vertical",
    isCore: false,
  },
  {
    id: "watersvc",
    name: "Water & Waste Services",
    nameAr: "المياه والنفايات",
    description: "Routes, subscriptions, tanker tickets, deposits",
    descriptionAr: "مسارات، اشتراكات، تذاكر وايت، عهد",
    icon: "Droplets",
    category: "vertical",
    isCore: false,
  },
  {
    id: "finserv",
    name: "Insurance Brokerage",
    nameAr: "وساطة التأمين",
    description: "Policies, renewals, commissions, collections",
    descriptionAr: "وثائق، تجديدات، عمولات، تحصيل",
    icon: "ShieldCheck",
    category: "vertical",
    isCore: false,
  },
  {
    id: "importexport",
    name: "Import/Export & Distribution",
    nameAr: "الاستيراد والتصدير",
    description: "Import files, landed cost, customs checklist",
    descriptionAr: "ملفات استيراد، تكلفة شاملة، مستندات جمركية",
    icon: "Container",
    category: "vertical",
    isCore: false,
  },

  // ADDITIONAL MODULES
  {
    id: "crm",
    name: "CRM",
    nameAr: "إدارة العملاء",
    description: "Leads, Opportunities, Activities, Pipeline",
    descriptionAr: "العملاء المحتملين، الفرص، الأنشطة",
    icon: "Users2",
    category: "additional",
    isCore: false,
  },
  {
    id: "projects",
    name: "Projects & Tasks",
    nameAr: "المشاريع والمهام",
    description: "Project management, Tasks, Timesheets, Billing",
    descriptionAr: "إدارة المشاريع، المهام، سجلات الوقت",
    icon: "FolderKanban",
    category: "additional",
    isCore: false,
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    nameAr: "التصنيع",
    description: "BOM, Production orders, Work orders, Quality",
    descriptionAr: "قائمة المواد، أوامر الإنتاج، أوامر العمل",
    icon: "Factory",
    category: "additional",
    isCore: false,
  },
  {
    id: "assets",
    name: "Asset Management",
    nameAr: "إدارة الأصول",
    description: "Fixed assets, Depreciation, Maintenance, Fleet",
    descriptionAr: "الأصول الثابتة، الاستهلاك، الصيانة",
    icon: "Package2",
    category: "additional",
    isCore: false,
  },
  {
    id: "helpdesk",
    name: "Helpdesk",
    nameAr: "خدمة العملاء",
    description: "Support tickets, Knowledge base, SLA",
    descriptionAr: "تذاكر الدعم، قاعدة المعرفة",
    icon: "MessageCircleQuestion",
    category: "additional",
    isCore: false,
  },
];

// MODULE CATEGORIES
export const MODULE_CATEGORIES = {
  core: { name: "Core Modules", nameAr: "الوحدات الأساسية", required: true },
  pos: { name: "Point of Sale", nameAr: "نقاط البيع", required: false },
  vertical: { name: "Industry Specific", nameAr: "حسب المجال", required: false },
  additional: { name: "Additional Features", nameAr: "ميزات إضافية", required: false },
};

// DEFAULT MODULES BY INDUSTRY
export const INDUSTRY_DEFAULTS = {
  retail: ["pos_retail", "crm"],
  wholesale: ["pos_retail", "crm"],
  manufacturing: ["manufacturing", "assets"],
  healthcare: ["healthcare", "pos_pharmacy"],
  construction: ["construction", "projects"],
  hospitality: ["hotel", "pos_restaurant"],
  education: ["education"],
  logistics: ["transport", "assets"],
  services: ["crm", "projects", "helpdesk"],
  technology: ["crm", "projects", "helpdesk"],
  workshop: ["workshop", "pos_retail"],
  salon: ["salon", "pos_retail"],
  gym: ["gym"],
  laundry: ["laundry", "pos_retail"],
  pharmacy: ["pharmacy", "pos_pharmacy"],
  ecommerce: ["ecommerce", "pos_retail"],
  hostel: ["hostel", "real_estate"],
  travel: ["travel", "crm"],
  aviation: ["aviation", "assets"],
  restaurant: ["pos_restaurant", "inventory"],
  real_estate: ["real_estate", "crm"],
  transport: ["transport", "assets"],
  // Saudi-market vertical workspaces
  fieldservice: ["fieldservice", "helpdesk", "crm"],
  events: ["events", "crm"],
  agency: ["agency", "crm", "projects"],
  professional: ["professional", "crm", "projects"],
  agriculture: ["agriculture", "assets"],
  energy: ["energy", "projects", "assets"],
  mining: ["mining", "assets"],
  marine: ["marine", "transport"],
  veterinary: ["veterinary", "crm", "pos_pharmacy"],
  nonprofit: ["nonprofit", "crm"],
  tailoring: ["tailoring", "pos_retail"],
  jewelry: ["jewelry", "pos_retail"],
  repair: ["repair", "pos_retail"],
  furniture: ["furniture", "manufacturing", "projects"],
  printing: ["printing", "crm"],
  watersvc: ["watersvc", "transport"],
  finserv: ["finserv", "crm"],
  importexport: ["importexport", "pos_wholesale", "transport"],
};
