import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/providers/trpc";
import { useAuth } from "@/hooks/useAuth";
import { CheckCircle2, XCircle, Clock, AlertCircle, Key, User } from "lucide-react";

export default function LicenseApprovalPage() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [rejectDialog, setRejectDialog] = useState<{ open: boolean; keyId: number; reason: string }>({ open: false, keyId: 0, reason: "" });
  const [tab, setTab] = useState("pending");

  const { data: pendingKeys, isLoading: pendingLoading } = trpc.licenseKey.approval.pendingKeys.useQuery(undefined, {
    enabled: user?.role === "admin" || user?.role === "super_admin",
  });
  const { data: allKeys } = trpc.licenseKey.approval.allKeys.useQuery({ status: tab !== "all" ? tab : undefined }, {
    enabled: (user?.role === "admin" || user?.role === "super_admin") && tab !== "pending",
  });
  const approveMutation = trpc.licenseKey.approval.approve.useMutation({
    onSuccess: () => { utils.licenseKey.approval.pendingKeys.invalidate(); utils.licenseKey.approval.allKeys.invalidate(); },
  });
  const rejectMutation = trpc.licenseKey.approval.reject.useMutation({
    onSuccess: () => { utils.licenseKey.approval.pendingKeys.invalidate(); utils.licenseKey.approval.allKeys.invalidate(); setRejectDialog({ open: false, keyId: 0, reason: "" }); },
  });

  const statusBadge = (status: string) => {
    const map: Record<string, { color: string; icon: any }> = {
      pending: { color: "bg-yellow-100 text-yellow-800", icon: Clock },
      approved: { color: "bg-blue-100 text-blue-800", icon: CheckCircle2 },
      active: { color: "bg-green-100 text-green-800", icon: CheckCircle2 },
      rejected: { color: "bg-red-100 text-red-800", icon: XCircle },
      revoked: { color: "bg-gray-100 text-gray-800", icon: AlertCircle },
      expired: { color: "bg-orange-100 text-orange-800", icon: AlertCircle },
    };
    const s = map[status] || map.pending;
    const Icon = s.icon;
    return <Badge variant="outline" className={s.color}><Icon className="w-3 h-3 mr-1" />{status}</Badge>;
  };

  if (user?.role !== "admin" && user?.role !== "super_admin") {
    return <div className="text-center py-12 text-slate-500">Access restricted to Admins and Super Admins.</div>;
  }

  const displayKeys = tab === "pending" ? pendingKeys : allKeys;

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">License Key Approval</h2>
        <p className="text-sm text-slate-500">Approve or reject license keys generated by resellers</p>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList>
          <TabsTrigger value="pending" className="relative">
            Pending
            {pendingKeys && pendingKeys.length > 0 && (
              <Badge className="ml-2 bg-yellow-500 text-white text-xs">{pendingKeys.length}</Badge>
            )}
          </TabsTrigger>
          <TabsTrigger value="approved">Approved</TabsTrigger>
          <TabsTrigger value="rejected">Rejected</TabsTrigger>
          <TabsTrigger value="all">All</TabsTrigger>
        </TabsList>

        {["pending", "approved", "rejected", "all"].map(t => (
          <TabsContent key={t} value={t}>
            <Card>
              <CardHeader><CardTitle>{t.charAt(0).toUpperCase() + t.slice(1)} Keys</CardTitle></CardHeader>
              <CardContent>
                {tab === "pending" && pendingLoading ? (
                  <p className="text-sm text-slate-500">Loading...</p>
                ) : !displayKeys?.length ? (
                  <p className="text-sm text-slate-500">No {t} license keys.</p>
                ) : (
                  <div className="space-y-3">
                    {displayKeys?.map((key: any) => (
                      <div key={key.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg border">
                        <div className="space-y-1">
                          <div className="flex items-center gap-2">
                            <span className="font-medium">{key.companyName}</span>
                            {statusBadge(key.status)}
                          </div>
                          <div className="flex items-center gap-4 text-xs text-slate-500">
                            <span className="flex items-center gap-1"><Key className="w-3 h-3" />{key.licenseKey.slice(0, 20)}...</span>
                            <span className="flex items-center gap-1"><User className="w-3 h-3" />Reseller #{key.resellerUserId}</span>
                            <span>{key.plan} | Users: {key.maxUsers} | Devices: {key.maxDevices}</span>
                          </div>
                          <p className="text-xs text-slate-400">
                            Created: {new Date(key.createdAt).toLocaleDateString()} | Expires: {new Date(key.expiresAt).toLocaleDateString()}
                          </p>
                          {key.reseller && (
                            <p className="text-xs text-slate-400">Reseller: {key.reseller.name} ({key.reseller.email})</p>
                          )}
                        </div>
                        {key.status === "pending" && (
                          <div className="flex items-center gap-2">
                            <Button size="sm" className="bg-green-600 hover:bg-green-700"
                              onClick={() => approveMutation.mutate({ id: key.id })}
                              disabled={approveMutation.isPending}>
                              <CheckCircle2 className="w-4 h-4 mr-1" />Approve
                            </Button>
                            <Button size="sm" variant="destructive"
                              onClick={() => setRejectDialog({ open: true, keyId: key.id, reason: "" })}>
                              <XCircle className="w-4 h-4 mr-1" />Reject
                            </Button>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        ))}
      </Tabs>

      <Dialog open={rejectDialog.open} onOpenChange={(o) => setRejectDialog(f => ({ ...f, open: o }))}>
        <DialogContent>
          <DialogHeader><DialogTitle>Reject License Key</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <p className="text-sm text-slate-500">Provide a reason for rejection (optional):</p>
            <Textarea value={rejectDialog.reason} onChange={e => setRejectDialog(f => ({ ...f, reason: e.target.value }))} placeholder="Reason for rejection..." />
            <div className="flex gap-2 justify-end">
              <Button variant="outline" onClick={() => setRejectDialog({ open: false, keyId: 0, reason: "" })}>Cancel</Button>
              <Button variant="destructive" disabled={rejectMutation.isPending}
                onClick={() => rejectMutation.mutate({ id: rejectDialog.keyId, reason: rejectDialog.reason || undefined })}>
                Confirm Reject
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
